[book]
title = "KCL语言技术内幕"
authors = ["国产语言爱好者"]
description = "KCL语言的设计与实现"
language = "zh"
multilingual = false
src = "."

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/china-programming-languages/kcl-internal-book"
edit-url-template = "https://github.com/china-programming-languages/kcl-internal-book/edit/master/{path}"
git-repository-icon = "fa-github"
